[[news]]
date = "2026-03"
content = "关于分子动力学角度与壳层感知深度势能模型的论文已投稿至 UAI 2026"

[[news]]
date = "2025-07"
content = "入职佛山论芯科技有限公司，担任研究助理"

[[news]]
date = "2025-04"
content = "一篇论文（MiDream）被 IJCNN 2025 接收"

[[news]]
date = "2024-12"
content = "一篇论文（ELF）被 ACM JDIQ 接收"
